#!/bin/bash

export LD_LIBRARY_PATH=/neowiz/lib
export SQLRELAY_CLIENT_TIMEOUT_CONNECT=30
export SQLRELAY_CLIENT_TIMEOUT_SHORT=300
export SQLRELAY_CLIENT_TIMEOUT_LONG=300

# 서버의 이름과 스크립트 이름이 동일해야 동작

me=`basename $0`
host=`hostname -s`

if [ $me != $host ] 
then
	echo "이 스크립트는 $me.nwz.kr안에서만 구동이 가능합니다."
	exit 0;
fi

case $1 in 
	start)
		if [ ! -f /neowiz/msh/pid/redis.pid ]; then
            echo "레디스 서버 구동"
            /neowiz/msh/redis/redis-server --daemonize yes --pidfile /neowiz/msh/pid/redis.pid --bind 127.0.0.1 --logfile /neowiz/msh/log/redis.log
        else
            echo "레디스 서버 구동 실패"
			exit -1;
        fi

		echo "몽고 디비 구동"
		/neowiz/msh/mongodb/mongod --bind_ip 127.0.0.1 --logpath /neowiz/msh/log/mongodb.log --logappend --pidfilepath /neowiz/msh/pid/ --dbpath /neowiz/msh/db/ --directoryperdb &

		;;

	stop)
		echo "몽고 디비 정지"
		/neowiz/msh/mongodb/mongod --shutdown --dbpath /neowiz/msh/db/


    if [ -f /neowiz/msh/pid/redis.pid ]; then
        echo "레디스 서버 정지"
        kill -15 `cat /neowiz/msh/pid/redis.pid`
        rm /neowiz/msh/pid/redis.pid
    fi

		;;
		
	*)
		echo "Usage: $0 {start|stop}" >&2
		;;

esac
