//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Option: light framework (CF/Silverlight) enabled
    
// Generated from: membership.proto
namespace ms
{
  [global::ProtoBuf.ProtoContract(Name=@"Version")]
  public partial class Version : global::ProtoBuf.IExtensible
  {
    public Version() {}
    
    private uint? _protocol;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint protocol
    {
      get { return _protocol?? (uint)150611; }
      set { _protocol = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool protocolSpecified
    {
      get { return this._protocol != null; }
      set { if (value == (this._protocol== null)) this._protocol = value ? this.protocol : (uint?)null; }
    }
    private bool ShouldSerializeprotocol() { return protocolSpecified; }
    private void Resetprotocol() { protocolSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private ms.MessageType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ms.MessageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ms.Request.Members _members = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"members", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ms.Request.Members members
    {
      get { return _members; }
      set { _members = value; }
    }
    private ms.Request.Token _token = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ms.Request.Token token
    {
      get { return _token; }
      set { _token = value; }
    }
    private ms.Request.Payment _payment = null;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"payment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ms.Request.Payment payment
    {
      get { return _payment; }
      set { _payment = value; }
    }
    private ms.Request.PushAllow _push_allow = null;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"push_allow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ms.Request.PushAllow push_allow
    {
      get { return _push_allow; }
      set { _push_allow = value; }
    }
  [global::ProtoBuf.ProtoContract(Name=@"Members")]
  public partial class Members : global::ProtoBuf.IExtensible
  {
    public Members() {}
    
    private string _app_key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"app_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string app_key
    {
      get { return _app_key; }
      set { _app_key = value; }
    }
    private string _udid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private ms.DevicePlatform _device_platform;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"device_platform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ms.DevicePlatform device_platform
    {
      get { return _device_platform; }
      set { _device_platform = value; }
    }
    private ms.ServicePlatform _service_platform;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"service_platform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ms.ServicePlatform service_platform
    {
      get { return _service_platform; }
      set { _service_platform = value; }
    }
    private string _gcm_token;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"gcm_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gcm_token
    {
      get { return _gcm_token?? ""; }
      set { _gcm_token = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool gcm_tokenSpecified
    {
      get { return this._gcm_token != null; }
      set { if (value == (this._gcm_token== null)) this._gcm_token = value ? this.gcm_token : (string)null; }
    }
    private bool ShouldSerializegcm_token() { return gcm_tokenSpecified; }
    private void Resetgcm_token() { gcm_tokenSpecified = false; }
    
    private ms.Request.Members.Facebook _facebook = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"facebook", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ms.Request.Members.Facebook facebook
    {
      get { return _facebook; }
      set { _facebook = value; }
    }
  [global::ProtoBuf.ProtoContract(Name=@"Facebook")]
  public partial class Facebook : global::ProtoBuf.IExtensible
  {
    public Facebook() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _access_token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string access_token
    {
      get { return _access_token; }
      set { _access_token = value; }
    }
    private string _email;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string email
    {
      get { return _email?? ""; }
      set { _email = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool emailSpecified
    {
      get { return this._email != null; }
      set { if (value == (this._email== null)) this._email = value ? this.email : (string)null; }
    }
    private bool ShouldSerializeemail() { return emailSpecified; }
    private void Resetemail() { emailSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"Token")]
  public partial class Token : global::ProtoBuf.IExtensible
  {
    public Token() {}
    
    private string _app_key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"app_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string app_key
    {
      get { return _app_key; }
      set { _app_key = value; }
    }
    private string _udid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private ms.DevicePlatform _device_platform;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"device_platform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ms.DevicePlatform device_platform
    {
      get { return _device_platform; }
      set { _device_platform = value; }
    }
    private ms.ServicePlatform _service_platform;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"service_platform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ms.ServicePlatform service_platform
    {
      get { return _service_platform; }
      set { _service_platform = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"Payment")]
  public partial class Payment : global::ProtoBuf.IExtensible
  {
    public Payment() {}
    
    private string _access_token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string access_token
    {
      get { return _access_token; }
      set { _access_token = value; }
    }
    private ms.ServicePlatform _service_platform;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"service_platform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ms.ServicePlatform service_platform
    {
      get { return _service_platform; }
      set { _service_platform = value; }
    }
    private string _inapp_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"inapp_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string inapp_id
    {
      get { return _inapp_id; }
      set { _inapp_id = value; }
    }
    private ms.Request.Payment.PlayStore _playstore = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"playstore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ms.Request.Payment.PlayStore playstore
    {
      get { return _playstore; }
      set { _playstore = value; }
    }
    private ms.Request.Payment.AppStore _appstore = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"appstore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ms.Request.Payment.AppStore appstore
    {
      get { return _appstore; }
      set { _appstore = value; }
    }
    private ms.Request.Payment.GameFlier _gameflier = null;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"gameflier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ms.Request.Payment.GameFlier gameflier
    {
      get { return _gameflier; }
      set { _gameflier = value; }
    }
  [global::ProtoBuf.ProtoContract(Name=@"PlayStore")]
  public partial class PlayStore : global::ProtoBuf.IExtensible
  {
    public PlayStore() {}
    
    private string _order_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"order_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string order_id
    {
      get { return _order_id; }
      set { _order_id = value; }
    }
    private string _package_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"package_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string package_name
    {
      get { return _package_name; }
      set { _package_name = value; }
    }
    private uint _purchase_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"purchase_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint purchase_time
    {
      get { return _purchase_time; }
      set { _purchase_time = value; }
    }
    private uint _purchase_state;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"purchase_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint purchase_state
    {
      get { return _purchase_state; }
      set { _purchase_state = value; }
    }
    private string _purchase_token;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"purchase_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string purchase_token
    {
      get { return _purchase_token; }
      set { _purchase_token = value; }
    }
    private string _developer_payload;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"developer_payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string developer_payload
    {
      get { return _developer_payload; }
      set { _developer_payload = value; }
    }
    private string _signature;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private string _original_json;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"original_json", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string original_json
    {
      get { return _original_json; }
      set { _original_json = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"AppStore")]
  public partial class AppStore : global::ProtoBuf.IExtensible
  {
    public AppStore() {}
    
    private string _order_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"order_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string order_id
    {
      get { return _order_id; }
      set { _order_id = value; }
    }
    private string _package_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"package_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string package_name
    {
      get { return _package_name; }
      set { _package_name = value; }
    }
    private uint _purchase_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"purchase_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint purchase_time
    {
      get { return _purchase_time; }
      set { _purchase_time = value; }
    }
    private uint _purchase_state;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"purchase_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint purchase_state
    {
      get { return _purchase_state; }
      set { _purchase_state = value; }
    }
    private string _purchase_token;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"purchase_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string purchase_token
    {
      get { return _purchase_token; }
      set { _purchase_token = value; }
    }
    private string _developer_payload;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"developer_payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string developer_payload
    {
      get { return _developer_payload; }
      set { _developer_payload = value; }
    }
    private string _signature;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private string _appstore_name;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"appstore_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string appstore_name
    {
      get { return _appstore_name?? ""; }
      set { _appstore_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool appstore_nameSpecified
    {
      get { return this._appstore_name != null; }
      set { if (value == (this._appstore_name== null)) this._appstore_name = value ? this.appstore_name : (string)null; }
    }
    private bool ShouldSerializeappstore_name() { return appstore_nameSpecified; }
    private void Resetappstore_name() { appstore_nameSpecified = false; }
    
    private string _receipt;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"receipt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string receipt
    {
      get { return _receipt?? ""; }
      set { _receipt = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool receiptSpecified
    {
      get { return this._receipt != null; }
      set { if (value == (this._receipt== null)) this._receipt = value ? this.receipt : (string)null; }
    }
    private bool ShouldSerializereceipt() { return receiptSpecified; }
    private void Resetreceipt() { receiptSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"GameFlier")]
  public partial class GameFlier : global::ProtoBuf.IExtensible
  {
    public GameFlier() {}
    
    private string _order_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"order_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string order_id
    {
      get { return _order_id; }
      set { _order_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"PushAllow")]
  public partial class PushAllow : global::ProtoBuf.IExtensible
  {
    public PushAllow() {}
    
    private string _access_token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string access_token
    {
      get { return _access_token; }
      set { _access_token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private ms.MessageType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ms.MessageType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _access_token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string access_token
    {
      get { return _access_token; }
      set { _access_token = value; }
    }
    private uint _expire_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"expire_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint expire_time
    {
      get { return _expire_time; }
      set { _expire_time = value; }
    }
    private ms.Response.Members _members = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"members", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ms.Response.Members members
    {
      get { return _members; }
      set { _members = value; }
    }
    private ms.Response.Payment _payment = null;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"payment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ms.Response.Payment payment
    {
      get { return _payment; }
      set { _payment = value; }
    }
  [global::ProtoBuf.ProtoContract(Name=@"Payment")]
  public partial class Payment : global::ProtoBuf.IExtensible
  {
    public Payment() {}
    
    private ms.ServicePlatform _service_platform;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service_platform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ms.ServicePlatform service_platform
    {
      get { return _service_platform; }
      set { _service_platform = value; }
    }
    private ulong _payment_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"payment_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong payment_id
    {
      get { return _payment_id; }
      set { _payment_id = value; }
    }
    private string _order_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"order_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string order_id
    {
      get { return _order_id; }
      set { _order_id = value; }
    }
    private string _developer_payload;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"developer_payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string developer_payload
    {
      get { return _developer_payload; }
      set { _developer_payload = value; }
    }
    private string _purchase_token;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"purchase_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string purchase_token
    {
      get { return _purchase_token; }
      set { _purchase_token = value; }
    }
    private string _inapp_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"inapp_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string inapp_id
    {
      get { return _inapp_id; }
      set { _inapp_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"Members")]
  public partial class Members : global::ProtoBuf.IExtensible
  {
    public Members() {}
    
    private ulong _member_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"member_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong member_id
    {
      get { return _member_id; }
      set { _member_id = value; }
    }
    private string _developer_payload;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"developer_payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string developer_payload
    {
      get { return _developer_payload; }
      set { _developer_payload = value; }
    }
    private readonly global::System.Collections.Generic.List<ms.Response.Payment> _payments = new global::System.Collections.Generic.List<ms.Response.Payment>();
    [global::ProtoBuf.ProtoMember(3, Name=@"payments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ms.Response.Payment> payments
    {
      get { return _payments; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"AppStatus")]
    public enum AppStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"APP_STATUS_DISABLE", Value=0)]
      APP_STATUS_DISABLE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"APP_STATUS_ENABLE", Value=1)]
      APP_STATUS_ENABLE = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProductStatus")]
    public enum ProductStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRODUCT_STATUS_DISABLE", Value=0)]
      PRODUCT_STATUS_DISABLE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRODUCT_STATUS_ENABLE", Value=1)]
      PRODUCT_STATUS_ENABLE = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PaymentStatus")]
    public enum PaymentStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYMENT_STATUS_PURCHASED", Value=1)]
      PAYMENT_STATUS_PURCHASED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYMENT_STATUS_CANCELED", Value=2)]
      PAYMENT_STATUS_CANCELED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYMENT_STATUS_EFFECTUATED", Value=10)]
      PAYMENT_STATUS_EFFECTUATED = 10
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MemberStatus")]
    public enum MemberStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEMBER_STATUS_INIT", Value=0)]
      MEMBER_STATUS_INIT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEMBER_STATUS_NORMAL", Value=1)]
      MEMBER_STATUS_NORMAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEMBER_STATUS_BLOCKED", Value=2)]
      MEMBER_STATUS_BLOCKED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEMBER_STATUS_DROP_OUT", Value=3)]
      MEMBER_STATUS_DROP_OUT = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DevicePlatform")]
    public enum DevicePlatform
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEVICE_PLATFORM_ANDROID", Value=10)]
      DEVICE_PLATFORM_ANDROID = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEVICE_PLATFORM_IOS", Value=20)]
      DEVICE_PLATFORM_IOS = 20
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ServicePlatform")]
    public enum ServicePlatform
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVICE_PLATFORM_PLAYSTORE", Value=10)]
      SERVICE_PLATFORM_PLAYSTORE = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVICE_PLATFORM_APPSTORE", Value=20)]
      SERVICE_PLATFORM_APPSTORE = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVICE_PLATFORM_GAMEFLIER", Value=30)]
      SERVICE_PLATFORM_GAMEFLIER = 30
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Currency")]
    public enum Currency
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENCY_USD", Value=0)]
      CURRENCY_USD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENCY_KRW", Value=1)]
      CURRENCY_KRW = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENCY_JPY", Value=2)]
      CURRENCY_JPY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENCY_TWD", Value=3)]
      CURRENCY_TWD = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MessageType")]
    public enum MessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEMBERS", Value=10)]
      MEMBERS = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOKEN", Value=20)]
      TOKEN = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYMENT", Value=30)]
      PAYMENT = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_ALLOW", Value=40)]
      PUSH_ALLOW = 40
    }
  
}