# admin service
## web/admin
mox628-admin:
  host: 10.69.11.118
  port: 8080
  debug: true
  upload_path: /neowiz/msh/web/admin/app/static/upload/
  secret_key: '309rjdfpjasdrj03q9jfdasr023wwfjsdafpjsd'

  log: 
    level: debug
    filename: /neowiz/msh/web/log/admin.log


# membership service
## web/membership
mox628-membership:
  debug: true
  secret_key: '309rjdfpjasdrj03q9jfdasr023wwfjsdafpjsd'
  expire_time: 3600 # sec

  log:
    level: debug
    filename: /neowiz/msh/web/log/membership.log

  app:
    id: 1
    key: 'ca4b0dd7fd262f3909ddb40f33a3493d41243112'
    secret: '9c03cc6056f044f3ae51f39b70ad02538c27c36724370ed36f0dcbd93cca313a'


mongodb:
  host: 'localhost'
  port: 27017
  db: 'ms-log'


redis-monitor:
  host: localhost
  port: 6379
  db: 7


redis-members:
  - host: localhost
    port: 6379
    db: 14

  - host: localhost
    port: 6379
    db: 15


# sqlrelay servers
sqlrelays:
  - host: dbcmobdev.nwz.kr
    port: 29438
    user: sqlruser
    pass: sqlrpass

  - host: dbcmobdev.nwz.kr
    port: 29438
    user: sqlruser
    pass: sqlrpass

  - host: dbcmobdev.nwz.kr
    port: 29438
    user: sqlruser
    pass: sqlrpass

  - host: dbcmobdev.nwz.kr
    port: 29438
    user: sqlruser
    pass: sqlrpass
